language: csharp
mono:
  - latest

solution: "Pokemon_3D_Server_Client/Pokemon_3D_Server_Client.sln"
  
install:
  - nuget restore "Pokemon_3D_Server_Client/Pokemon_3D_Server_Client.sln"

script:
  - xbuild /p:Configuration=Release "Pokemon_3D_Server_Client/Pokemon_3D_Server_Client.sln"
