language: csharp
mono:
  - latest

solution: "Pokemon.3D.Server.Client.sln"
  
install:
  - nuget restore "Pokemon.3D.Server.Client.sln"

script:
  - xbuild /p:Configuration=Release "Pokemon.3D.Server.Client.sln"
