language: csharp
mono:
  - latest

solution: "Pokemon.3D.Server.Client.sln"

git:
  submodules: false
  
before_install:
  - git submodule foreach --recursive git pull origin master
  
install:
  - nuget restore "Pokemon.3D.Server.Client.sln"

script:
  - xbuild /p:Configuration=Release "Pokemon.3D.Server.Client.sln"
