os: Visual Studio 2015

configuration:
- Release
platform: Any CPU

before_build:
- nuget restore Pokemon_3D_Server_Client\Pokemon_3D_Server_Client.sln

build:
  project: Pokemon_3D_Server_Client\Pokemon_3D_Server_Client.sln
  verbosity: minimal
