version: 0.54.1.{build}
branches:
  only:
  - master
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: git submodule update --init --recursive
before_build:
- ps: nuget restore Pokemon.3D.Server.Client.sln
build:
  project: Pokemon.3D.Server.Client.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Pokemon.3D.Server.Client.GUI/bin/Release
  name: Pokemon.3D.Server.Client.GUI
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: "Pokémon 3D Server Client v$(appveyor_build_version)"
  auth_token:
    secure: UyngIeXJ3Cv4yHkTI7+2/PuW35IVx8Nn9yRh8wIEDLXRaG+OGNkqzhftWfjPbHNc
  artifact: Pokemon.3D.Server.Client.GUI
  draft: false
  prerelease: true