name: 01 - Prep Overlay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prep-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prep:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore Pokemon.3D.Server.Core/Pokemon.3D.Server.Core.csproj

      - name: Create overlay
        run: mkdir ci-overlay

      - name: Cache overlay (unique key)
        uses: actions/cache/save@v4
        with:
          path: ci-overlay
          key: overlay-${{ github.sha }}-${{ github.run_id }}
