name: 02 Build Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-server:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Ensure SmartThreadPool
        run: |
          nuget install SmartThreadPool.dll -Version 2.3.0 -OutputDirectory packages

      - name: Create Directory.Build.props
        run: |
          @"
          <Project>
            <ItemGroup>
              <Reference Include="SmartThreadPool">
                <HintPath>$(MSBuildThisFileDirectory)packages\SmartThreadPool.dll.2.3.0\lib\net45\SmartThreadPool.dll</HintPath>
                <Private>True</Private>
              </Reference>
            </ItemGroup>
            <PropertyGroup>
              <_StubDir>$(MSBuildThisFileDirectory)Pokemon.3D.Server.Core\_GeneratedStubs\</_StubDir>
            </PropertyGroup>
            <ItemGroup>
              <Compile Include="$(_StubDir)*.cs" Condition="Exists($(_StubDir))" />
            </ItemGroup>
          </Project>
          "@ | Out-File Directory.Build.props -Encoding utf8

      - name: Create Directory.Build.targets
        run: |
          @"
          <Project>
            <ItemGroup>
              <Compile Remove="**\Packages\*.cs" />
            </ItemGroup>
          </Project>
          "@ | Out-File Directory.Build.targets -Encoding utf8

      - name: Generate stub files
        shell: pwsh
        run: |
          $stubDir = "Pokemon.3D.Server.Core\_GeneratedStubs"
          New-Item -ItemType Directory -Force -Path $stubDir | Out-Null

          $stub = @"
          namespace BuildStubs {
            public enum PackageTypes { Unknown = 0 }
            public static class DataItems { public const string None = "None"; }
            public enum BeginCreateFileStatus { Unknown = 0 }
          }
          namespace Pokemon.Server_Client_Listener.Packages {
            using BuildStubs;
            public class Package {
              public object Client { get; set; }
              public int Id { get; set; }
              public string Name { get; set; }
              public byte[] Data { get; set; }
              public PackageTypes Type { get; set; }
            }
            public static class PackageHandler {
              public static void Send(Package p) { }
              public static Package Parse(byte[] b) { return new Package(); }
            }
          }
          "@
          $stub | Out-File (Join-Path $stubDir "Packages.Stubs.cs") -Encoding utf8

      - name: Restore NuGet packages
        run: nuget restore Pokemon.3D.Server.Core/Pokemon.3D.Server.Core.csproj

      - name: Build Server Core
        run: msbuild "Pokemon.3D.Server.Core/Pokemon.3D.Server.Core.csproj" /p:Configuration=Release /m /v:m

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: Pokemon3D-Server
          path: Pokemon.3D.Server.Core/bin/Release/
