name: 03 - Build Client

on:
  workflow_run:
    workflows: ["02 - Build Server"]
    types: [completed]

jobs:
  build-client:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore overlay cache
        uses: actions/cache/restore@v4
        with:
          path: ci-overlay
          key: overlay-${{ github.event.workflow_run.head_sha }}-${{ github.event.workflow_run.id }}
          restore-keys: |
            overlay-${{ github.event.workflow_run.head_sha }}-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build Client GUI
        run: |
          msbuild Pokemon.3D.Server.Client.GUI/Pokemon.3D.Server.Client.GUI.csproj /p:Configuration=Debug /m /v:m

      - name: Upload client artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: Pokemon.3D.Server.Client.GUI/bin/Debug
